---
name: "Item Warehouse: Website"
description: A warehouse with an API on the front of it
version: 1.0.3
slug: item_warehouse_website
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: before
options:
  api_url:
schema:
  api_url: str
ports:
  8003/tcp: 3000
