---
name: "Item Warehouse: Website"
description: A warehouse with an API on the front of it
version: 1.4.0
slug: item_warehouse_website
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
options:
  api_base_url: http://homeassistant.local:8002
schema:
  api_base_url: str
ingress: true
ingress_port: 3000
ports:
  3000/tcp: 8003
webui: http://[HOST]:[PORT:3000]