---
version: '3'

services:
  run:
    build:
      args:
        - BUILD_FROM=homeassistant/amd64-base:latest
    env_file:
      - .env
    ports:
      - 8003:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
