---
name: 'CI: Validation'

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  ci-validation:
    name: 'CI: Validation'
    uses: worgarside/github-config-files/.github/workflows/__ci_validation.yml@main
    with:
      build-branch: '${{ github.ref }}'
      build-type: 'node'
      node-build-directory: 'item_warehouse_website'
      python-version: ''
      unit-test: ''
    secrets: inherit
