name: ESLint

on:
  push:
    branches: 
      - develop
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: "18"

      - name: Install Dependencies
        run: cd item_warehouse_website && npm install

      - name: Run ESLint
        run: npm run lint